### ISSUE TITLE
Execute Cron Job error 

### ISSUE THREAD

**Issue by phmlr** [ProHill/VRS-flights-db#1]
PHP Notice:  Trying to get property of non-object in /home/dutchradar/domains/dutchradar.nl/public_html/flights/getTrackMlat.php on line 54
PHP Warning:  Invalid argument supplied for foreach() in /home/dutchradar/domains/dutchradar.nl/public_html/flights/getTrackMlat.php on line 54

foreach( $data->acList as $aircraft )

I'am using PHP 5.5.30

**Comment by ProHill** [comment]
Those are notices and warnings, and can be ignored, although I'll look at handling them. Are you getting rows inserted into your mlat_lookup table?

**Comment by phmlr** [comment]
okay i ignore that,

And stil i recive no data in MYSQL. 
Error on file: http://dutchradar.nl/flights/flightimport.php
He can't find the flights.csv
i'am running on a Ubuntu server whit Directadmin software 
this is the config.php

```
<?php
// Change the following lines to reflect your database information, 
// then rename this file to config.php
$databasehost = "localhost";
$databaseusername= " -- ";
$databasepassword = " -- ";
$databasename = " -- ";
$flightsdatabasetable = "flightstable";
$lookup_table = "track_mlat_lookup";
$csvfile = "/flights.csv";
date_default_timezone_set('Europe/Amsterdam');
$vrshostname = "127.0.0.1";
$vrsport = "360";
// If VRS is password protected, enter the credentials in the following 2 fields, otherwise leave blank
$vrsusername = "";
$vrspassword = "";
?>
```

**Comment by ProHill** [comment]
Did you do the setup to export the csv from the VRS sqlite database and copy it to your web server?  Also, I notice you have "/flights.csv" - does the file exist, and is it really in the root directory?

**Comment by phmlr** [comment]
Yes the file is exported by the Windows task every 5 minutes (db-query.vbs). 
The last line in dv-query.bat have i deleted, i'am syncing the CSV file with allway sync to the webserver.

The file can be find by browser on http://dutchradar.nl/flights/flights.csv 
on the server from the root access is the pad: /home/dutchradar/domains/dutchradar.nl/public_html/flights

**Comment by ProHill** [comment]
Put the whole path in the config file (/home/dutchradar... etc)

**Comment by phmlr** [comment]
$csvfile = "/home/dutchradar/domains/dutchradar.nl/public_html/flights/flights.csv"; (Not working 500 Error. 
$csvfile = "./home/dutchradar/domains/dutchradar.nl/public_html/flights/flights.csv"; Whit dash at the begin (File not found)

**Comment by ProHill** [comment]
I just downloaded your csv file and was able to import it.  What happens if you manually run "php flightimport.php" ?

**Comment by phmlr** [comment]
that's the way how i'am trying it. 
http://dutchradar.nl/flights/flightimport.php

**Comment by ProHill** [comment]
There may be a php configuration causing this. Check to see if open_basedir is set in php.ini.

**Comment by phmlr** [comment]
; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most se; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; http://php.net/open-basedir
;open_basedir =nse if used in a per-directory
; or per-virtualhost web server configuration file.
; http://php.net/open-basedir
;open_basedir =

**Comment by phmlr** [comment]
When i look in the http.conf File: php_admin_value open_basedir /home/dutchradar/:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/

**Comment by ProHill** [comment]
In that case, try this in your config.php:
$csvfile = "domains/dutchradar.nl/public_html/flights/flights.csv";

**Comment by phmlr** [comment]
Same Problem, i have installed Xampp tot test but also the same problem.

**Comment by ProHill** [comment]
Is this your own server, or are you using a hosting provider?  If the latter, you may want to check with them to see if there are other restrictions getting in the way.

**Comment by phmlr** [comment]
Yes this is my own web server, and Xampp was running on my personal computer and not on the server

**Comment by ProHill** [comment]
Try getting rid of that open_basedir statement in your http.conf, restarting your webserver, then go back to using the full path.

**Comment by phmlr** [comment]
Problem not solved, 
it looks like a problem in the import script. Is there a another way ?

**Comment by ProHill** [comment]
I'm not sure what to tell you - I just loaded up a local copy of xampp and it worked fine.  If you want me to take a look, I'd be happy to - I'll just need ssh access to your web server.

**Comment by phmlr** [comment]
I can not give you SSH acces, i'am going to look for a another way.
Thanks for your help.
