### ISSUE TITLE
mlat_cleanup issue

### ISSUE THREAD

**Issue by ghost** [ProHill/VRS-flights-db#2]
When I type the command `source path/to/mlat_cleanup.sql` with the correct source, I get this mysql error: `ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Delete old MLAT lookup rows' ON SCHEDULE EVERY 1 HOUR STARTS NOW() ON COMPLETIO' at line 1`

**Comment by ProHill** [comment]
Thank you - fixed.
