### ISSUE TITLE
PDOException’ with message ‘SQLSTATE[42000] when db_query.vbs is run

### ISSUE THREAD

**Issue by techfixpros** [ProHill/VRS-flights-db#4]
I am getting the following error message when after the db_query.vbs script is run:

PHP Fatal error: Uncaught exception ‘PDOException’ with message ‘SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version’ in /var/www/html/vrs/flightimport.php:25
Stack trace:
#0 /var/www/html/vrs/flightimport.php(25): PDO->exec(‘?LOAD DATA LOCA…’)
#1 {main}

thrown in /var/www/html/vrs/flightimport.php on line 25

The web server is on a Linux Mint 17.2 machine, while VRS and the whole sqlite folder are on a WinXP machine. The flights.csv file is pushed successfully via pscp to the linux box.

MySQL version:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.5.50-0ubuntu0.14.04.1 – (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Apache version:
Apache/2.4.7 (Ubuntu)
Database client version: libmysql – 5.5.49
PHP extension: mysqli

**Comment by ProHill** [comment]
You need Load data local in file configured in MySQL. See http://dev.mysql.com/doc/refman/5.7/en/load-data-local.html

**Comment by techfixpros** [comment]
Thank you. I also referenced http://forum.virtualradarserver.co.uk/viewtopic.php?t=617&start=10 to get the native driver installed as well and that fixed it. Tables are now populated.
